# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PioDrive' do

pod 'konashi-ios-sdk', :git => 'git@github.com:YUKAI/konashi-ios-sdk.git',:branch => 'feature/spi'

end

target 'KoooTest' do

end

